const menu=[
    {
    id: 1,
    image:"images/PaneerTikka.jpg ",
    name:"paneer tikka",
    category:"starters",
    price:"₹ 85",
    description:
    "Paneer Tikka is a popular and delicious tandoori snack where paneer (Indian cottage cheese cubes) are marinated in a spiced yogurt-based marinade, arranged on skewers and grilled in the oven",
},
{
    id: 2,
    image:"images/HaraBharaKebab.jpg ",
    name:"Hara Bhara Kebab",
    category:"starters",
    price:"₹ 75",
    description:
    "Hara Bhara Kabab is a very popular snack of North Indian fried patties made with spinach, peas and potatoes. This word means a kabab full of greens .Here the green colored veggies are spinach and green peas. These are nutritious since they have the best of both spinach and green peas.",
}, 
{
    id: 3,
    image:"images/ChaapTikka.jpg",
    name:"Tandoori Chaap Tikka",
    category:"starters",
    price:"₹ 80",
    description:"Soya chaap tikka is the vegetarian version of the famous chicken tikka. The process to make soya chaap tikka might look long but is actually the simplest one.Healthy and perfect snack for any get-together.",

},
{
    id: 4,
    image:"images/CrispyCorns.jpg",
    name:"Crispy Corns",
    category:"starters",
    price:"₹ 80",
    description:"It is a simple snack where corn is coated with maida, rice flour, corn flour, salt and black pepper powder mixture and then deep fried until it changes its colour to golden brown and becomes crispy. ",
},
{
    id: 5,
    image:"images/vegnoodles.jpg",
    name:"veg Noodles",
    category:"Chinese",
    price:"₹ 85",
    description:" an easy and simple vegetable-based noodles  made with simple plain wheat noodles. it is an popular indo chinese version of noodles made with a generous amount of chopped veggies. ",
},
{
    id: 6,
    image:"images/Momos.jpg",
    name:"Momos",
    category:"Chinese",
    price:"₹ 60",
    description:"Momos are a popular street food in northern parts of India. These are also known as Dim Sum and are basically dumplings made from flour with a savory stuffing.",
},
{
    id: 7,
    image:"image/Manchurian.jpg",
    name:"Manchurian",
    category:"Chinese",
    price:"₹ 60",
    description:"Manchurian is a class of Indo-chinese dishes made by roughly chopping and deep-frying a main ingredient like chicken, cauliflower (gobi), prawns, fish, mutton or paneer and then sautéeing it in a sauce flavored with soy sauce. Manchurian is the result of the adaptation of Chinese cooking and seasoning techniques to suit Indian tastes and has become a staple of Indian Chinese cuisine.",
},
{
    id: 8,
    image:"images/ChilliPaneer.jpg",
    name:"Chilli Paneer",
    category:"Chinese",
    price:"₹ 60",
    description:"Firstly paneer is coated in corn starch batter and fried until crisp. Then a fresh chilli sauce is made by sauteing ingredients like garlic, capsicum and spring onions. Next red chili sauce, soya sauce and vinegar are added to make the sauce.",
},
{
    id: 9,
    image:"images/HakkaNoodles.jpg",
    name:"Hakka Noodles",
    category:"Chinese",
    price:"₹ 80",
    description:"ove thy noodles will take on a new meaning altogether once you have tried the extremely popular Vegetable Hakka Noodles. Commonly served in most Indian restaurants and street-side eateries, these Indo-Chinese Hakka Noodles are a perfect balance of crunch, relish, and goodness.",
},
{
    id: 10,
    image:"images/ShahiPaneer.jpg",
    name:"Shahi Paneer",
    category:"Main Course",
    price:"₹ 100",
    description:"This Shahi Paneer is deliciously rich and creamy, making it one of the most popular recipes in Mughlai cuisine. Fresh, unmelting cheese is married with a creamy gravy, perfect for serving with naan or roti. “Shahi” means “royalty,” and I can promise this dish is fit for a King!",
},
{
    id: 11,
    image:"images/Dalmakhani.jpg",
    name:"Dal Makhni",
    category:"Main Course",
    price:"₹ 90",
    description:"This Dal Makhani recipe is a restaurant style version with subtle smoky flavors and creaminess of the lentils. If you love authentic Punjabi food then you are going to love this Dal Makhani even more.",
},
{
    id: 12,
    image:"images/MalaiKofta.jpg",
    name:"Malai Kofta",
    category:"Main Course",
    price:"₹ 95",
    description:"Malai Kofta is a delicious dish of fried balls of potato and paneer in a rich and creamy mild gravy made with sweet onions and tomatoes. This melt-in-your-mouth recipe is a labor of love, but one that is well worth it. Learn to make this special Indian meal with me!",
},
{
    id: 13,
    image:"images/DumAloo.jpg",
    name:"Dum Aloo",
    category:"Main Course",
    price:"₹ 95",
    description:"Spicy and delish is this Kashmiri Dum Aloo where baby potatoes are simmered (dum cooked) in a spicy curd (yogurt) based gravy or sauce. This is a delicious recipe from the Kashmiri cuisine.",
},
];
export default menu;